version: "3.9"

services:
  db:
    image: postgres:15
    container_name: praesidium-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praesidium
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: praesidium-backend
    env_file: .env   # Optional, safe to leave even if not used
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/praesidium-front:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: